---
name: Publish Artifacts test
on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Select environment to deploy'
        required: true
        type: choice
        options:
          - QA
          - Prod
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - develop
      - sprint/*

    paths-ignore:
      - '.github/**'
      - '*.md'

jobs:
   publish-artifacts:
     name: Publish Artifacts
     runs-on: ubuntu-latest
     permissions:
       id-token: write
       contents: read
       packages: write
     steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish Artifacts
        # if: github.ref == 'refs/heads/main'
        # if: ${{github.event_name == 'workflow_dispatch' && github.event.inputs.Environment == 'Prod' }}
        if: github.ref == 'refs/heads/main' || [${{github.event_name == 'workflow_dispatch' && github.event.inputs.Environment == 'Prod' }}]
        run: |
          echo ${{github.ref}}
          echo ${{github.event_name}}
          echo ${{github.event.inputs.Environment}}
          echo ${{github.ref == 'refs/heads/main'}}
          echo ${{github.event_name == 'workflow_dispatch' && github.event.inputs.Environment == 'Prod'}}
      # - name: Setup Java
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '17'
      #     distribution: 'adopt'

      # - name: Run Test Cases
      #   run: |
      #     mvn clean install

      # - name: Publish Artifacts
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     mvn --batch-mode deploy

      
